### ISSUE TITLE
There is an explanation about CSS.

### ISSUE THREAD

**Issue by masahirokjp** [Rashad-Yusifov/vue-nuxt-accordion#1]
Thank you for creating this useful tool. I was able to implement the accordion successfully.

For one thing, it will be very easy to handle if you have a list ready regarding CSS.

I have changed two CSS components.

.accordion-head {
  background: #ffffff !important; 
}

.accordion-content {
  background: #ffffff !important;
}

You can check it out in Chrome's element validation, but it's better to have it in order.

**Comment by rashad-yusifov** [comment]
Hi, thank you for feedback.
